### ISSUE TITLE
HD-events password is ONLY 6 chars long (instead of 8 or more characters)

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/hd-events#103]
@Cealtea 

For the following event:
http://events.hackerdojo.com/event/5814916040622080-women-who-code-wwc-sv-techinal-leadership-development-workshop

The events password did not work for SSID: **HD-Events**. 

The password given to them is only 6 characters long (**fowb1z**). I think the password has to be at a minimum of 8 characters. 

The join button is not even enable when I enter the 6 character password.
![screen shot 2016-09-24 at 1 03 22 pm](https://cloud.githubusercontent.com/assets/5217007/18810948/0a0bc530-8258-11e6-8370-dc41ef5894be.png)

As soon as I enter 2 more characters the join button turns on:
![screen shot 2016-09-24 at 1 03 34 pm](https://cloud.githubusercontent.com/assets/5217007/18810950/15b28b1c-8258-11e6-846e-47c8ac5948de.png)

**Comment by cherukumilli** [comment]
Jonathan had the following to say:

```
On Sat, Sep 24, 2016 at 1:59 PM Jonathan Dai <jonathan.dai@hackerdojo.com> wrote:
Hi, 

The password for HD-Events is "hackerdojo". Afterwards you will be prompted to type in the unique password for the event.

- Jonathan 
```

**Comment by cherukumilli** [comment]
based on Jonathan's feedback...the fastest to resolve this problem is by updating the instructions to the event organizer. I will submit a PR with updated instructions.

**Comment by Cealtea** [comment]
We could also make the SSID open without password.

**Comment by cherukumilli** [comment]
@Cealtea 
If we make it open then do they still have to enter the password generated by the new code?
or
is HD-Events open to all?

**Comment by Cealtea** [comment]
If we make it open, they will only have to enter the password of the event
in the login window.
-- 
Celine Bursztein
------------------------------------------------------
http://celine.im
@cealtea <https://twitter.com/cealtea> on Twitter, +Celine Bursztein
<https://plus.google.com/+Celine%20Bursztein> on Google+

**Comment by cherukumilli** [comment]
I like this idea of just letting them enter the event password ONLY.

If there is no downside then we should make HD-Events open and have them enter only the event password to get access to the Hacker Dojo internet.

**Comment by Cealtea** [comment]
I can do that from where I am I have the admin access on the meraki system.

-- 
Celine Bursztein
------------------------------------------------------
http://celine.im
@cealtea <https://twitter.com/cealtea> on Twitter, +Celine Bursztein
<https://plus.google.com/+Celine%20Bursztein> on Google+

**Comment by cherukumilli** [comment]
@Cealtea 
I just changed it to `Open (no encryption)` in the meraki system. Please feel free to change it if I didn't change it correctly.

**Comment by Cealtea** [comment]
Great! Thanks. Now people will only have to enter the event password when
the wifi splash page shows up.
-- 
Celine Bursztein
------------------------------------------------------
http://celine.im
@cealtea <https://twitter.com/cealtea> on Twitter, +Celine Bursztein
<https://plus.google.com/+Celine%20Bursztein> on Google+
