### ISSUE TITLE
Refresh page every one hour on the client side

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/hd-events#97]
__Problem Description:__
events.hackerdojo.com page that is shown at the entrance is not updating every morning. It shows data from Wednesday because no one manually updated the page.

__Solution__
Add a timer that will refresh the page every 60 minutes. This change will:
- show events starting from today
- show updates to existing events (cancelled, time changes, etc...)

**Comment by Cealtea** [comment]
I can do it! but I don't know how to assign the ticket to me!

**Comment by cherukumilli** [comment]
@Cealtea 
I added you as a collaborator.
Please make changes locally and test it before submitting your pull request.

**Comment by Cealtea** [comment]
Sure! I already did the modification. I need to test locally. I will let you know.

**Comment by cherukumilli** [comment]
@Cealtea 
I see your code got merged into the master. I think the feature you implemented might be supported by the current browsers but it is deprecated. Please check https://www.w3.org/TR/WCAG10-HTML-TECHS/#meta-element.

We should be ok for now but think about other way to address this problem.

**Comment by cherukumilli** [comment]
@Cealtea 
I wonder if we should add an extension / addon like in the article: http://www.online-tech-tips.com/computer-tips/automatically-refresh-web-pages-in-browser/

This will be in addition to the code that you fixed.
thoughts?

**Comment by Cealtea** [comment]
@cherukumilli Yes the meta is an old trick but it's a quick fix for now since it is still supported by most browsers.
Using a chrome extension is a good idea. I will install some of them on my computer and choose one which seems to work fine. Do you know the chrome version on the big screen in the lobby?

**Comment by Cealtea** [comment]
@cherukumilli I propose using Easy Auto Refresh with a 5-6hours timer maybe more. https://chrome.google.com/webstore/detail/easy-auto-refresh/aabcgdmkeabbnleenpncegpcngjpnjkc?hl=en

**Comment by cherukumilli** [comment]
@Cealtea 
Sounds good. Let's go with the Easy Auto Refresh. Please let me know if you can do it when you are at the dojo or request @Russell-Zhang or @sunnguyen1 to help install this extension or add on and set it up to refresh every 5 hours.

**Comment by Cealtea** [comment]
@cherukumilli I will do the install tomorrow. Do you want me to remove the meta element in the page?

**Comment by cherukumilli** [comment]
No. Let's keep the meta tag for now.

**Comment by cherukumilli** [comment]
Closing this issue as we moved to a new location. Will open another issue if we need a different way to address the refresh functionality
